# ----
# Site

google_analytics_key:
permalink: pretty

gems:
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE

collections:
  projects:
    title: Documentation
    permalink: /docs/:slug
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      images: /logo.png
      layout: null