# ----
# Site

google_analytics_key:
title: NTwitch Documentation
description: A .net core implementation of the https://twitch.tv/ version 5 api, strongly based on Discord.Net.
url: https://aux.github.io/NTwitch/
logo: logo.png
permalink: pretty

gems:
  - jekyll-seo-tag
  - jekyll-last-modified-at

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /docs/:slug
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      images: logo.png
      layout: null